# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-06-07 18:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_course_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='videos',
            field=models.FileField(default='', upload_to='videos/%Y/%m', verbose_name='视频'),
        ),
        migrations.AlterField(
            model_name='course',
            name='teacher',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='organizations.Teacher', verbose_name='所教教师'),
        ),
    ]
