# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-06-11 07:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0007_video_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='videos',
            field=models.FileField(blank=True, default='', null=True, upload_to='videos/%Y/%m', verbose_name='视频'),
        ),
    ]
