# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-06-19 09:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0009_auto_20180614_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='org',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='organizations.Organizations', verbose_name='课程机构'),
        ),
    ]
