# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-05-31 09:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20180530_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='address',
            field=models.CharField(max_length=100, verbose_name='地址'),
        ),
    ]
