# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-06-02 12:54
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20180531_0916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailcaptcha',
            name='send_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='发送时间'),
        ),
        migrations.AlterField(
            model_name='viewpager',
            name='url',
            field=models.URLField(verbose_name='图片链接'),
        ),
    ]
