# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-06-02 17:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20180602_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailcaptcha',
            name='send_type',
            field=models.CharField(choices=[('register', '注册'), ('forget', '忘记密码')], default='register', max_length=10, verbose_name='类型'),
        ),
    ]
