# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-06-14 18:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20180602_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viewpager',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='viewpager/%Y/%m', verbose_name='图片'),
        ),
    ]
