# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-06-14 18:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20180614_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viewpager',
            name='url',
            field=models.CharField(max_length=200, verbose_name='图片链接'),
        ),
    ]
