# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-06-04 09:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizations',
            name='category',
            field=models.CharField(choices=[('pxjg', '培训机构'), ('gx', '高校'), ('gr', '个人')], default='pxjg', max_length=20, verbose_name='机构类型'),
        ),
        migrations.AlterField(
            model_name='organizations',
            name='image',
            field=models.ImageField(upload_to='organizations/%Y/%m', verbose_name='logo'),
        ),
    ]
