# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-06-19 09:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0006_organizations_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='organizations',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organizations.Organizations', verbose_name='所属机构'),
        ),
    ]
